# risk.py
import streamlit as st
from google.cloud import bigquery
import os
import pandas as pd
import plotly.express as px

def get_risk_data(project_id, dataset):
    client = bigquery.Client(project=project_id)
    query = f"""
        SELECT r.*, s.name as server_name, s.workload_type, s.os 
        FROM `{project_id}.{dataset}.risk_scores` r
        JOIN `{project_id}.{dataset}.servers` s ON r.server_id = s.server_id
        ORDER BY r.overall_risk_score DESC
    """
    
    try:
        df = client.query(query).to_dataframe()
        if not df.empty:
            return df
    except Exception as e:
        print(f"Failed to query risk scores: {e}")
        
    # Return mock data
    mock_risk = [
        {"server_name": "DB-ORACLE-PROD-01", "overall_risk_score": 9.2, "risk_level": "critical", "recommended_strategy": "relocate", "complexity_score": 8.5, "business_criticality": 10.0, "estimated_effort_days": 5, "strategy_rationale": "Oracle DB with custom configuration. Relocate to Google Cloud Bare Metal Solution for licensing compliance."},
        {"server_name": "APP-PAYMENT-PROD-01", "overall_risk_score": 8.8, "risk_level": "critical", "recommended_strategy": "refactor", "complexity_score": 7.8, "business_criticality": 10.0, "estimated_effort_days": 15, "strategy_rationale": "Core payment engine. Refactor to microservices on GKE with Cloud Spanner for global transaction consistency."},
        {"server_name": "LB-NGINX-01", "overall_risk_score": 4.5, "risk_level": "medium", "recommended_strategy": "rehost", "complexity_score": 3.0, "business_criticality": 8.0, "estimated_effort_days": 2, "strategy_rationale": "Standard load balancer. Rehost to Compute Engine behind Cloud Load Balancing."},
        {"server_name": "WEBAPP-PROD-01", "overall_risk_score": 5.2, "risk_level": "medium", "recommended_strategy": "rehost", "complexity_score": 4.0, "business_criticality": 8.0, "estimated_effort_days": 2, "strategy_rationale": "Prod web host. Rehost to Compute Engine instances with auto-scaling."},
        {"server_name": "DB-MYSQL-STAGE-01", "overall_risk_score": 6.8, "risk_level": "high", "recommended_strategy": "replatform", "complexity_score": 6.0, "business_criticality": 4.0, "estimated_effort_days": 3, "strategy_rationale": "MySQL database. Replatform to managed Cloud SQL for MySQL to reduce ops overhead."},
        {"server_name": "CACHE-REDIS-PROD-01", "overall_risk_score": 5.8, "risk_level": "medium", "recommended_strategy": "replatform", "complexity_score": 4.5, "business_criticality": 8.0, "estimated_effort_days": 2, "strategy_rationale": "Redis cache. Replatform to Memorystore for Redis."},
        {"server_name": "QUEUE-RABBIT-PROD-01", "overall_risk_score": 5.2, "risk_level": "medium", "recommended_strategy": "replatform", "complexity_score": 4.0, "business_criticality": 8.0, "estimated_effort_days": 2, "strategy_rationale": "RabbitMQ queue. Replatform to Google Cloud Pub/Sub."},
        {"server_name": "INFRA-LDAP-01", "overall_risk_score": 6.4, "risk_level": "medium", "recommended_strategy": "repurchase", "complexity_score": 5.0, "business_criticality": 9.0, "estimated_effort_days": 3, "strategy_rationale": "Shared LDAP server. Repurchase with Google Cloud Identity SaaS model."},
        {"server_name": "LEGACY-ARCHIVE-01", "overall_risk_score": 2.2, "risk_level": "low", "recommended_strategy": "retire", "complexity_score": 2.0, "business_criticality": 1.0, "estimated_effort_days": 1, "strategy_rationale": "Server is powered off with no active traffic. Recommending Retire."}
    ]
    return pd.DataFrame(mock_risk)

def render():
    project_id = os.getenv("GCP_PROJECT_ID")
    dataset = os.getenv("BIGQUERY_DATASET", "dami_v3")
    
    st.markdown("<h1 class='gradient-text'>Risk Scoring & 7R Assessment</h1>", unsafe_allow_html=True)
    st.write("Examine workload risk classifications generated by our BQML model and the resulting Gartner 7R migration strategy decisions.")
    st.write("---")
    
    df = get_risk_data(project_id, dataset)
    
    # Summary Metrics
    col1, col2, col3, col4 = st.columns(4)
    
    crit_count = len(df[df["risk_level"].isin(["critical", "high"])])
    rehost_count = len(df[df["recommended_strategy"] == "rehost"])
    replatform_count = len(df[df["recommended_strategy"] == "replatform"])
    refactor_count = len(df[df["recommended_strategy"] == "refactor"])
    
    with col1:
        st.metric("High/Critical Risk Servers", f"{crit_count} VMs", delta="Requires Wave 4+", delta_color="inverse")
    with col2:
        st.metric("Rehost (Lift & Shift)", f"{rehost_count} VMs", delta="Standard VMs")
    with col3:
        st.metric("Replatform (Managed DB/SaaS)", f"{replatform_count} VMs", delta="Cloud SQL / Memorystore")
    with col4:
        st.metric("Refactor (Cloud Native)", f"{refactor_count} VMs", delta="GKE / Microservices")
        
    st.write("---")
    
    # Plotly Visuals
    ccol1, ccol2 = st.columns(2)
    
    with ccol1:
        st.subheader("Gartner 7R Migration Strategies Share")
        fig_7r = px.pie(
            df, 
            names="recommended_strategy", 
            title="Strategic Allocation Breakdown",
            color_discrete_sequence=px.colors.qualitative.Dark2
        )
        fig_7r.update_layout(plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)", font_color="#e2e8f0")
        st.plotly_chart(fig_7r, use_container_width=True)
        
    with ccol2:
        st.subheader("Complexity vs Business Criticality")
        fig_scatter = px.scatter(
            df, 
            x="complexity_score", 
            y="business_criticality",
            color="risk_level",
            size="estimated_effort_days",
            hover_name="server_name",
            color_discrete_map={"critical": "#ea4335", "high": "#ff6d01", "medium": "#fbbc04", "low": "#34a853"},
            title="Risk Mapping (Bubble Size = Effort in Days)"
        )
        fig_scatter.update_layout(plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)", font_color="#e2e8f0")
        st.plotly_chart(fig_scatter, use_container_width=True)
        
    st.write("---")
    
    # Risk Score Horizontal Bar Chart — visual impact!
    st.subheader("Risk Score Ranking")
    import plotly.graph_objects as go
    
    sorted_df = df.sort_values("overall_risk_score", ascending=True)
    colors = []
    for level in sorted_df["risk_level"]:
        if level == "critical":
            colors.append("#ef4444")
        elif level == "high":
            colors.append("#f97316")
        elif level == "medium":
            colors.append("#eab308")
        else:
            colors.append("#22c55e")
    
    fig_bar = go.Figure(go.Bar(
        x=sorted_df["overall_risk_score"],
        y=sorted_df["server_name"],
        orientation="h",
        marker=dict(
            color=colors,
            line=dict(color="rgba(0,0,0,0.3)", width=1)
        ),
        text=[f"{s:.1f} — {r}" for s, r in zip(sorted_df["overall_risk_score"], sorted_df["recommended_strategy"])],
        textposition="auto",
        textfont=dict(color="#e2e8f0", size=11),
        hovertemplate="<b>%{y}</b><br>Risk: %{x:.1f}<br>%{text}<extra></extra>"
    ))
    fig_bar.update_layout(
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        font_color="#e2e8f0",
        height=max(300, len(sorted_df) * 40),
        margin=dict(l=180, r=20, t=20, b=40),
        xaxis=dict(title="Overall Risk Score (0-10)", range=[0, 10], gridcolor="rgba(99,102,241,0.1)"),
        yaxis=dict(title=""),
        bargap=0.25
    )
    st.plotly_chart(fig_bar, use_container_width=True)
    
    st.write("---")
    
    # Detailed Risk Table
    st.subheader("Detailed Assessment Register")
    
    # Add column config for better display
    display_cols = [
        "server_name", "overall_risk_score", "risk_level", 
        "recommended_strategy", "complexity_score", 
        "business_criticality", "estimated_effort_days", "strategy_rationale"
    ]
    available_cols = [c for c in display_cols if c in df.columns]
    
    st.dataframe(
        df[available_cols],
        use_container_width=True,
        hide_index=True,
        column_config={
            "server_name": st.column_config.TextColumn("Server", width="medium"),
            "overall_risk_score": st.column_config.ProgressColumn(
                "Risk Score", min_value=0, max_value=10, format="%.1f"
            ),
            "risk_level": st.column_config.TextColumn("Level", width="small"),
            "recommended_strategy": st.column_config.TextColumn("7R Strategy", width="small"),
            "complexity_score": st.column_config.NumberColumn("Complexity", format="%.1f"),
            "business_criticality": st.column_config.NumberColumn("Criticality", format="%.0f"),
            "estimated_effort_days": st.column_config.NumberColumn("Effort (days)", format="%d"),
            "strategy_rationale": st.column_config.TextColumn("Rationale", width="large"),
        }
    )
    
    st.write("---")
    
    # --- BQML Model Training & Evaluation ---
    st.subheader("🧠 BigQuery ML — Risk Prediction Model")
    st.write("Train a BQML Logistic Regression model to predict complex migration strategies based on server resource metrics. Once trained, `ML.PREDICT` is automatically used in future risk assessments.")
    
    bqml_col1, bqml_col2 = st.columns([1, 1])
    
    with bqml_col1:
        st.markdown("""
        <div style="
            background: rgba(66, 133, 244, 0.08);
            border: 1px solid rgba(66, 133, 244, 0.3);
            border-radius: 10px;
            padding: 16px;
        ">
            <div style="font-weight: 700; color: #4285f4; font-size: 1rem;">📐 Model Architecture</div>
            <div style="font-size: 0.8rem; color: #cbd5e1; margin-top: 8px;">
                <b>Type:</b> Logistic Regression (LOGISTIC_REG)<br/>
                <b>Features:</b> vcpu, ram_gb, cpu_utilization_avg, ram_utilization_avg<br/>
                <b>Label:</b> Complex strategy needed (Refactor/Replatform/Relocate = 1, else 0)<br/>
                <b>Training Data:</b> servers ⨝ risk_scores tables<br/>
                <b>Integration:</b> ML.PREDICT blends with heuristic scoring
            </div>
        </div>
        """, unsafe_allow_html=True)
    
    with bqml_col2:
        # Check if model already exists
        model_status = "Not Trained"
        model_color = "#f59e0b"
        try:
            client = bigquery.Client(project=project_id)
            client.get_model(f"{project_id}.{dataset}.migration_risk_model")
            model_status = "Trained ✅"
            model_color = "#10b981"
        except Exception:
            pass
        
        st.markdown(f"""
        <div style="
            background: rgba(16, 185, 129, 0.08);
            border: 1px solid rgba(16, 185, 129, 0.3);
            border-radius: 10px;
            padding: 16px;
        ">
            <div style="font-weight: 700; color: {model_color}; font-size: 1rem;">🔄 Model Status: {model_status}</div>
            <div style="font-size: 0.8rem; color: #cbd5e1; margin-top: 8px;">
                When trained, <code>ML.PREDICT</code> runs automatically during risk assessment.<br/>
                Predictions adjust heuristic scores: complex workloads get a risk boost, simple workloads get reduced scores.
            </div>
        </div>
        """, unsafe_allow_html=True)
    
    st.write("")
    
    train_col1, train_col2 = st.columns(2)
    with train_col1:
        if st.button("🚀 Train BQML Risk Model", use_container_width=True):
            with st.spinner("Training BQML Logistic Regression model on BigQuery... This may take 30-60 seconds."):
                from agents.risk_scorer import RiskScorerAgent
                scorer = RiskScorerAgent()
                result = scorer.train_bqml_model()
            if "successfully" in result.lower():
                st.success(result)
                st.rerun()
            else:
                st.error(result)
    
    with train_col2:
        if st.button("📊 Evaluate Model Performance", use_container_width=True):
            with st.spinner("Running ML.EVALUATE on trained model..."):
                from agents.risk_scorer import RiskScorerAgent
                scorer = RiskScorerAgent()
                eval_result = scorer.evaluate_bqml_model()
            
            if "error" not in eval_result:
                eval_col1, eval_col2, eval_col3, eval_col4 = st.columns(4)
                with eval_col1:
                    st.metric("Accuracy", f"{eval_result.get('accuracy', 0):.2%}")
                with eval_col2:
                    st.metric("Precision", f"{eval_result.get('precision', 0):.2%}")
                with eval_col3:
                    st.metric("Recall", f"{eval_result.get('recall', 0):.2%}")
                with eval_col4:
                    st.metric("F1 Score", f"{eval_result.get('f1_score', 0):.2%}")
            else:
                st.warning(f"Model not trained yet or evaluation failed: {eval_result['error']}")
    
    # ── F5: BQML Probability Bands ──
    st.write("---")
    st.subheader("📊 BQML Confidence & Probability Bands")
    st.caption("Shows the BQML model's prediction confidence for each server — not just the recommended strategy, "
               "but how confident the model is. Low-confidence predictions indicate borderline workloads that need manual review.")
    
    try:
        client_prob = bigquery.Client(project=project_id)
        # Run ML.PREDICT to get probability distributions
        prob_query = f"""
            SELECT 
                s.server_id,
                s.name AS server_name,
                s.vcpu,
                s.ram_gb,
                s.cpu_utilization_avg,
                s.ram_utilization_avg,
                s.workload_type,
                p.predicted_is_complex,
                p.predicted_is_complex_probs
            FROM ML.PREDICT(
                MODEL `{project_id}.{dataset}.migration_risk_model`,
                (
                    SELECT server_id, name, vcpu, ram_gb, 
                           cpu_utilization_avg, ram_utilization_avg,
                           workload_type,
                           CASE 
                               WHEN r.recommended_strategy IN ('refactor', 'replatform', 'relocate') THEN 1
                               ELSE 0
                           END AS is_complex
                    FROM `{project_id}.{dataset}.servers` s
                    LEFT JOIN `{project_id}.{dataset}.risk_scores` r ON s.server_id = r.server_id
                )
            ) p
            JOIN `{project_id}.{dataset}.servers` s ON p.server_id = s.server_id
            ORDER BY s.server_id
        """
        prob_df = client_prob.query(prob_query).to_dataframe()
        
        if not prob_df.empty and "predicted_is_complex_probs" in prob_df.columns:
            # Extract probability for "complex" class
            confidences = []
            for _, row in prob_df.iterrows():
                probs = row.get("predicted_is_complex_probs", [])
                if isinstance(probs, list) and len(probs) > 0:
                    # Find prob for class 1 (complex)
                    complex_prob = 0.5
                    for p in probs:
                        if isinstance(p, dict) and p.get("label") == 1:
                            complex_prob = p.get("prob", 0.5)
                            break
                    confidences.append({
                        "server_name": row.get("server_name", "Unknown"),
                        "predicted": int(row.get("predicted_is_complex", 0)),
                        "complex_probability": complex_prob,
                        "confidence": max(complex_prob, 1 - complex_prob),
                        "vcpu": row.get("vcpu", 0),
                        "ram_gb": row.get("ram_gb", 0),
                    })
                else:
                    confidences.append({
                        "server_name": row.get("server_name", "Unknown"),
                        "predicted": int(row.get("predicted_is_complex", 0)),
                        "complex_probability": 0.5,
                        "confidence": 0.5,
                        "vcpu": row.get("vcpu", 0),
                        "ram_gb": row.get("ram_gb", 0),
                    })
            
            conf_df = pd.DataFrame(confidences)
            
            # Probability bands chart
            pb1, pb2 = st.columns([3, 2])
            
            with pb1:
                
                sorted_conf = conf_df.sort_values("complex_probability", ascending=True)
                bar_colors = []
                for p in sorted_conf["complex_probability"]:
                    if p >= 0.8:
                        bar_colors.append("#ef4444")  # High confidence complex
                    elif p >= 0.6:
                        bar_colors.append("#f97316")  # Moderate complex
                    elif p >= 0.4:
                        bar_colors.append("#fbbf24")  # Borderline
                    elif p >= 0.2:
                        bar_colors.append("#3b82f6")  # Moderate simple
                    else:
                        bar_colors.append("#10b981")  # High confidence simple
                
                fig_prob = go.Figure(go.Bar(
                    x=sorted_conf["complex_probability"],
                    y=sorted_conf["server_name"],
                    orientation="h",
                    marker_color=bar_colors,
                    text=[f"{p:.0%}" for p in sorted_conf["complex_probability"]],
                    textposition="auto",
                    textfont=dict(color="#e2e8f0", size=9),
                    hovertemplate="<b>%{y}</b><br>P(Complex): %{x:.1%}<extra></extra>",
                ))
                fig_prob.update_layout(
                    title=dict(text="P(Complex Migration) — BQML Prediction", font=dict(color="#e2e8f0", size=13)),
                    xaxis=dict(title="Probability of Complex Migration", range=[0, 1],
                              gridcolor="rgba(100,116,139,0.1)"),
                    yaxis=dict(title=""),
                    paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                    font=dict(color="#e2e8f0"),
                    height=max(350, len(sorted_conf) * 28),
                    margin=dict(l=170, r=20, t=40, b=40),
                )
                # Add confidence zones
                fig_prob.add_vrect(x0=0.4, x1=0.6, fillcolor="rgba(251,191,36,0.08)", 
                                  line_width=0, annotation_text="⚠️ Borderline", 
                                  annotation_position="top")
                st.plotly_chart(fig_prob, use_container_width=True)
            
            with pb2:
                # Confidence distribution
                high_conf = len(conf_df[conf_df["confidence"] >= 0.8])
                mid_conf = len(conf_df[(conf_df["confidence"] >= 0.6) & (conf_df["confidence"] < 0.8)])
                low_conf = len(conf_df[conf_df["confidence"] < 0.6])
                
                st.markdown(f"""
                <div style="background: rgba(30,30,47,0.5); border-radius: 10px; padding: 16px;">
                    <div style="font-weight: 700; color: #e2e8f0; font-size: 0.95rem; margin-bottom: 12px;">
                        Confidence Distribution
                    </div>
                    <div style="margin-bottom: 8px;">
                        <span style="color: #10b981; font-weight: 600;">🟢 High Confidence (≥80%):</span>
                        <span style="color: #e2e8f0; font-weight: 700; float: right;">{high_conf} servers</span>
                    </div>
                    <div style="margin-bottom: 8px;">
                        <span style="color: #fbbf24; font-weight: 600;">🟡 Moderate (60-80%):</span>
                        <span style="color: #e2e8f0; font-weight: 700; float: right;">{mid_conf} servers</span>
                    </div>
                    <div style="margin-bottom: 12px;">
                        <span style="color: #ef4444; font-weight: 600;">🔴 Low Confidence (<60%):</span>
                        <span style="color: #e2e8f0; font-weight: 700; float: right;">{low_conf} servers</span>
                    </div>
                    <div style="border-top: 1px solid rgba(99,102,241,0.15); padding-top: 8px; font-size: 0.78rem; color: #94a3b8;">
                        Low confidence predictions indicate borderline workloads that may benefit from 
                        manual review or additional feature data.
                    </div>
                </div>
                """, unsafe_allow_html=True)
                
                # Average confidence
                avg_conf = conf_df["confidence"].mean() * 100
                st.metric("Average Model Confidence", f"{avg_conf:.1f}%")
                
                # Borderline servers warning
                borderline = conf_df[(conf_df["complex_probability"] >= 0.4) & (conf_df["complex_probability"] <= 0.6)]
                if not borderline.empty:
                    st.warning(f"⚠️ {len(borderline)} servers in the borderline zone (40-60%) — recommend manual review")
        else:
            st.info("Run ML.PREDICT to see probability distributions. The model is trained — click 'Evaluate Model Performance' above.")
    except Exception as e:
        st.info(f"BQML probability bands require a trained model. Train the model above to see confidence distributions. ({type(e).__name__})")

if __name__ == "__main__":
    render()

