import React, { useEffect, useState, useMemo } from 'react';
import axios from 'axios';
import { Layers, Clock, Server, ChevronDown, ChevronRight } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Cell, PieChart, Pie } from 'recharts';

const WAVE_COLORS = { 'wave-1': '#10b981', 'wave-2': '#3b82f6', 'wave-3': '#f59e0b', 'wave-4': '#ef4444', 'wave-5': '#8b5cf6' };
const RISK_COLORS = { critical: '#ef4444', high: '#f97316', medium: '#eab308', low: '#22c55e' };

export default function MigrationWavePlan() {
  const [waves, setWaves] = useState([]);
  const [loading, setLoading] = useState(true);
  const [expandedWaves, setExpandedWaves] = useState({});

  useEffect(() => {
    axios.get('http://localhost:8000/api/waves')
      .then(res => setWaves(res.data || []))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  // Group by wave
  const grouped = useMemo(() => {
    const groups = {};
    waves.forEach(w => {
      const wid = w.wave_id || 'unassigned';
      if (!groups[wid]) groups[wid] = { wave_id: wid, wave_name: w.wave_name || wid, servers: [] };
      groups[wid].servers.push(w);
    });
    return Object.values(groups);
  }, [waves]);

  const totalServers = waves.length;
  const totalEffort = waves.reduce((sum, w) => sum + (w.effort_days || 0), 0);
  const uniqueWaves = grouped.length;

  const toggleWave = (wid) => setExpandedWaves(prev => ({ ...prev, [wid]: !prev[wid] }));

  if (loading) {
    return (
      <main className="flex-1 bg-[#0b0f19] flex items-center justify-center h-full">
        <div className="text-indigo-400 text-xl font-bold animate-pulse">Loading Wave Plan...</div>
      </main>
    );
  }

  return (
    <main className="flex-1 bg-[#0b0f19] text-white flex flex-col h-full overflow-y-auto p-10 pb-20 custom-scrollbar relative z-10">
      <header className="mb-8">
        <h1 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400 tracking-tight mb-2">
          Migration Wave Plan
        </h1>
        <p className="text-slate-400 font-medium">
          View and manage the phased migration waves generated by the AI Wave Planner agent.
        </p>
      </header>
      <div className="h-px bg-white/10 w-full mb-8" />

      {/* KPIs */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="bg-[#131826] rounded-xl p-5 border border-white/[0.05]">
          <div className="text-sm text-slate-400 mb-1">Total Waves</div>
          <div className="text-3xl font-bold text-white">{uniqueWaves}</div>
        </div>
        <div className="bg-[#131826] rounded-xl p-5 border border-white/[0.05]">
          <div className="text-sm text-slate-400 mb-1">Total Servers Assigned</div>
          <div className="text-3xl font-bold text-white">{totalServers}</div>
        </div>
        <div className="bg-[#131826] rounded-xl p-5 border border-white/[0.05]">
          <div className="text-sm text-slate-400 mb-1">Total Effort</div>
          <div className="text-3xl font-bold text-white">{totalEffort} Days</div>
        </div>
        <div className="bg-[#131826] rounded-xl p-5 border border-white/[0.05]">
          <div className="text-sm text-slate-400 mb-1">Avg Effort / Wave</div>
          <div className="text-3xl font-bold text-white">{uniqueWaves > 0 ? (totalEffort / uniqueWaves).toFixed(1) : 0} Days</div>
        </div>
      </div>

      {/* WAVE CHARTS */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
        <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg">
          <h3 className="text-lg font-bold text-white mb-4">Servers per Wave</h3>
          <div className="h-[250px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={grouped.map(w => ({ name: w.wave_id, servers: w.servers.length, effort: w.servers.reduce((s, sv) => s + (sv.effort_days || 0), 0) }))}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                <XAxis dataKey="name" stroke="#64748b" tick={{fontSize:11}} />
                <YAxis stroke="#64748b" tick={{fontSize:11}} />
                <Tooltip contentStyle={{backgroundColor:'#0f172a', borderColor:'#1e293b', color:'#fff'}} />
                <Bar dataKey="servers" name="Servers" barSize={30} radius={[4,4,0,0]}>
                  {grouped.map((w, i) => <Cell key={i} fill={WAVE_COLORS[w.wave_id] || '#6366f1'} />)}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
        <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg">
          <h3 className="text-lg font-bold text-white mb-4">Strategy Distribution</h3>
          <div className="h-[250px]">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={(() => { const counts = {}; waves.forEach(w => { counts[w.strategy] = (counts[w.strategy] || 0) + 1; }); return Object.entries(counts).map(([name, value]) => ({name, value})); })()} cx="50%" cy="50%" innerRadius={50} outerRadius={100} paddingAngle={2} dataKey="value" label={({name, percent}) => `${name} ${(percent*100).toFixed(0)}%`}>
                  {(() => { const counts = {}; waves.forEach(w => { counts[w.strategy] = (counts[w.strategy] || 0) + 1; }); return Object.entries(counts).map(([_, __], i) => <Cell key={i} fill={['#6366f1','#10b981','#f59e0b','#ef4444','#3b82f6'][i % 5]} />); })()}
                </Pie>
                <Tooltip contentStyle={{backgroundColor:'#0f172a', borderColor:'#1e293b', color:'#fff'}} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* WAVE TIMELINE */}
      <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg mb-8">
        <h3 className="text-xl font-bold text-white mb-6">Wave Timeline</h3>
        <div className="flex gap-4 overflow-x-auto pb-4 custom-scrollbar">
          {grouped.map((wave, i) => {
            const color = WAVE_COLORS[wave.wave_id] || '#6366f1';
            const waveEffort = wave.servers.reduce((s, sv) => s + (sv.effort_days || 0), 0);
            return (
              <div key={wave.wave_id} className="flex-shrink-0 w-64 bg-slate-900/50 rounded-xl border border-white/10 p-5 relative overflow-hidden">
                <div className="absolute top-0 left-0 w-full h-1" style={{ backgroundColor: color }} />
                <div className="text-xs font-bold uppercase tracking-wider mb-2" style={{ color }}>{wave.wave_id}</div>
                <div className="text-sm font-bold text-white mb-3">{wave.wave_name || wave.wave_id}</div>
                <div className="flex justify-between text-xs text-slate-400 mb-3">
                  <span className="flex items-center gap-1"><Server className="w-3 h-3" /> {wave.servers.length} servers</span>
                  <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {waveEffort}d effort</span>
                </div>
                <div className="flex flex-wrap gap-1">
                  {wave.servers.slice(0, 4).map((s, j) => (
                    <span key={j} className="text-[10px] bg-slate-800 text-slate-300 px-2 py-0.5 rounded-full">{s.server_name}</span>
                  ))}
                  {wave.servers.length > 4 && <span className="text-[10px] bg-slate-800 text-slate-400 px-2 py-0.5 rounded-full">+{wave.servers.length - 4} more</span>}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* DETAILED WAVE BREAKDOWN */}
      <div className="space-y-4">
        {grouped.map((wave) => {
          const color = WAVE_COLORS[wave.wave_id] || '#6366f1';
          const isExpanded = expandedWaves[wave.wave_id] !== false; // default open
          return (
            <div key={wave.wave_id} className="bg-[#131826] rounded-xl border border-white/[0.05] shadow-lg overflow-hidden">
              <button onClick={() => toggleWave(wave.wave_id)} className="w-full p-5 flex items-center justify-between hover:bg-white/[0.02] transition-colors">
                <div className="flex items-center gap-4">
                  <div className="w-3 h-3 rounded-full" style={{ backgroundColor: color }} />
                  <div className="text-left">
                    <div className="font-bold text-white">{wave.wave_name || wave.wave_id}</div>
                    <div className="text-xs text-slate-400">{wave.servers.length} servers • {wave.servers.reduce((s, sv) => s + (sv.effort_days || 0), 0)} days total effort</div>
                  </div>
                </div>
                {isExpanded ? <ChevronDown className="w-5 h-5 text-slate-400" /> : <ChevronRight className="w-5 h-5 text-slate-400" />}
              </button>
              {isExpanded && (
                <div className="border-t border-white/5">
                  <table className="w-full text-xs text-left">
                    <thead className="text-slate-400 bg-slate-900/50">
                      <tr>
                        <th className="p-3 font-semibold">Server</th>
                        <th className="p-3 font-semibold">Strategy</th>
                        <th className="p-3 font-semibold">Risk Level</th>
                        <th className="p-3 font-semibold">Effort (days)</th>
                      </tr>
                    </thead>
                    <tbody className="text-slate-300 divide-y divide-white/5">
                      {wave.servers.map((s, i) => (
                        <tr key={i} className="hover:bg-white/5">
                          <td className="p-3 font-medium text-indigo-300">{s.server_name}</td>
                          <td className="p-3 capitalize">{s.strategy || 'N/A'}</td>
                          <td className="p-3">
                            <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs font-medium
                              ${s.risk_level === 'critical' ? 'bg-red-500/10 text-red-400' : 
                                s.risk_level === 'high' ? 'bg-orange-500/10 text-orange-400' :
                                s.risk_level === 'medium' ? 'bg-yellow-500/10 text-yellow-400' :
                                'bg-green-500/10 text-green-400'}`}>
                              <span className={`w-1.5 h-1.5 rounded-full ${
                                s.risk_level === 'critical' ? 'bg-red-500' :
                                s.risk_level === 'high' ? 'bg-orange-500' :
                                s.risk_level === 'medium' ? 'bg-yellow-500' : 'bg-green-500'}`} />
                              {s.risk_level || 'N/A'}
                            </span>
                          </td>
                          <td className="p-3">{s.effort_days || 'N/A'}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </main>
  );
}
