import React, { useEffect, useState, useMemo } from 'react';
import api from '../lib/api';
import axios from 'axios';
import { AlertTriangle, ShieldAlert, Target, ArrowRightLeft, Trash2 } from 'lucide-react';
import {
  PieChart, Pie, Cell, Tooltip, ResponsiveContainer,
  BarChart, Bar, XAxis, YAxis, CartesianGrid,
  ScatterChart, Scatter, ZAxis
} from 'recharts';

const RISK_COLORS = { critical: '#ef4444', high: '#f97316', medium: '#eab308', low: '#22c55e' };
const STRATEGY_COLORS = ['#6366f1', '#10b981', '#f59e0b', '#ec4899', '#3b82f6', '#14b8a6', '#f43f5e'];

export default function RiskAssessment() {
  const [risks, setRisks] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/api/risk/scores')
      .then(res => setRisks(res.data || []))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  // KPIs
  const critCount = risks.filter(r => r.risk_level === 'critical' || r.risk_level === 'high').length;
  const rehostCount = risks.filter(r => r.recommended_strategy === 'rehost').length;
  const replatformCount = risks.filter(r => r.recommended_strategy === 'replatform').length;
  const refactorCount = risks.filter(r => r.recommended_strategy === 'refactor').length;

  // 7R Pie
  const strategyData = useMemo(() => {
    const counts = risks.reduce((acc, r) => {
      acc[r.recommended_strategy] = (acc[r.recommended_strategy] || 0) + 1;
      return acc;
    }, {});
    return Object.entries(counts).map(([name, value]) => ({ name, value }));
  }, [risks]);

  // Risk bar chart (sorted ascending for horizontal layout)
  const riskBarData = useMemo(() => {
    return [...risks].sort((a, b) => a.overall_risk_score - b.overall_risk_score);
  }, [risks]);

  // Scatter data
  const scatterData = useMemo(() => {
    return risks.map(r => ({
      x: r.complexity_score || 0,
      y: r.business_criticality || 0,
      z: r.estimated_effort_days || 1,
      name: r.server_name,
      risk: r.risk_level
    }));
  }, [risks]);

  if (loading) {
    return (
      <main className="flex-1 bg-[#0b0f19] flex items-center justify-center h-full">
        <div className="text-indigo-400 text-xl font-bold animate-pulse">Analyzing Risk Profiles...</div>
      </main>
    );
  }

  return (
    <main className="flex-1 bg-[#0b0f19] text-white flex flex-col h-full overflow-y-auto p-10 pb-20 custom-scrollbar relative z-10">
      {/* HEADER */}
      <header className="mb-8">
        <h1 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400 tracking-tight mb-2">
          Risk Scoring & 7R Assessment
        </h1>
        <p className="text-slate-400 font-medium">
          Examine workload risk classifications generated by our BQML model and the resulting Gartner 7R migration strategy decisions.
        </p>
      </header>
      <div className="h-px bg-white/10 w-full mb-8" />

      {/* KPI CARDS */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="bg-[#131826] rounded-xl p-5 border border-white/[0.05]">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm text-slate-400 font-medium">High/Critical Risk</span>
            <ShieldAlert className="w-5 h-5 text-red-400" />
          </div>
          <div className="text-3xl font-bold text-white">{critCount} VMs</div>
          <div className="text-xs text-red-400 font-bold mt-1">↑ Requires Wave 4+</div>
        </div>
        <div className="bg-[#131826] rounded-xl p-5 border border-white/[0.05]">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm text-slate-400 font-medium">Rehost (Lift & Shift)</span>
            <ArrowRightLeft className="w-5 h-5 text-blue-400" />
          </div>
          <div className="text-3xl font-bold text-white">{rehostCount} VMs</div>
          <div className="text-xs text-blue-400 font-bold mt-1">Standard VMs</div>
        </div>
        <div className="bg-[#131826] rounded-xl p-5 border border-white/[0.05]">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm text-slate-400 font-medium">Replatform (Managed)</span>
            <Target className="w-5 h-5 text-amber-400" />
          </div>
          <div className="text-3xl font-bold text-white">{replatformCount} VMs</div>
          <div className="text-xs text-amber-400 font-bold mt-1">Cloud SQL / Memorystore</div>
        </div>
        <div className="bg-[#131826] rounded-xl p-5 border border-white/[0.05]">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm text-slate-400 font-medium">Refactor (Cloud Native)</span>
            <Trash2 className="w-5 h-5 text-emerald-400" />
          </div>
          <div className="text-3xl font-bold text-white">{refactorCount} VMs</div>
          <div className="text-xs text-emerald-400 font-bold mt-1">GKE / Microservices</div>
        </div>
      </div>
      <div className="h-px bg-white/10 w-full mb-8" />

      {/* CHARTS ROW */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-10">
        {/* 7R Pie */}
        <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg">
          <h3 className="text-xl font-bold text-white mb-2">Gartner 7R Migration Strategies Share</h3>
          <p className="text-xs text-slate-400 mb-4">Strategic Allocation Breakdown</p>
          <div className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={strategyData} cx="50%" cy="50%" innerRadius={60} outerRadius={110} paddingAngle={2} dataKey="value" label={({name, percent}) => `${name} ${(percent*100).toFixed(0)}%`}>
                  {strategyData.map((_, i) => <Cell key={i} fill={STRATEGY_COLORS[i % STRATEGY_COLORS.length]} />)}
                </Pie>
                <Tooltip contentStyle={{backgroundColor:'#0f172a', borderColor:'#1e293b', color:'#fff'}} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Scatter */}
        <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg">
          <h3 className="text-xl font-bold text-white mb-2">Complexity vs Business Criticality</h3>
          <p className="text-xs text-slate-400 mb-4">Risk Mapping (Bubble Size = Effort in Days)</p>
          <div className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <ScatterChart margin={{ top: 10, right: 10, bottom: 10, left: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                <XAxis type="number" dataKey="x" name="Complexity" domain={[0, 10]} stroke="#64748b" tick={{fontSize:11}} label={{value:'Complexity Score', position:'insideBottomRight', offset:-5, fill:'#94a3b8', fontSize:11}} />
                <YAxis type="number" dataKey="y" name="Criticality" domain={[0, 10]} stroke="#64748b" tick={{fontSize:11}} label={{value:'Business Criticality', angle:-90, position:'insideLeft', fill:'#94a3b8', fontSize:11}} />
                <ZAxis type="number" dataKey="z" range={[60, 400]} />
                <Tooltip contentStyle={{backgroundColor:'#0f172a', borderColor:'#1e293b', color:'#fff'}} formatter={(val, name) => [val, name]} />
                <Scatter data={scatterData} fill="#6366f1">
                  {scatterData.map((entry, i) => <Cell key={i} fill={RISK_COLORS[entry.risk] || '#6366f1'} />)}
                </Scatter>
              </ScatterChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* RISK SCORE RANKING */}
      <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg mb-10">
        <h3 className="text-xl font-bold text-white mb-4">Risk Score Ranking</h3>
        <div className="h-[400px]">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart layout="vertical" data={riskBarData} margin={{ top: 0, right: 30, left: 120, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="rgba(255,255,255,0.05)" />
              <XAxis type="number" domain={[0, 10]} stroke="#64748b" tick={{fontSize:11}} axisLine={false} tickLine={false} />
              <YAxis type="category" dataKey="server_name" stroke="#64748b" tick={{fontSize:11, fill:'#cbd5e1'}} axisLine={false} tickLine={false} width={120} />
              <Tooltip contentStyle={{backgroundColor:'#0f172a', borderColor:'#1e293b', color:'#fff'}} formatter={(val, name, props) => [`${val.toFixed(1)} — ${props.payload.recommended_strategy}`, 'Risk Score']} />
              <Bar dataKey="overall_risk_score" barSize={16} radius={[0, 4, 4, 0]}>
                {riskBarData.map((entry, i) => <Cell key={i} fill={RISK_COLORS[entry.risk_level] || '#6366f1'} />)}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* DETAILED TABLE */}
      <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg mb-10">
        <h3 className="text-xl font-bold text-white mb-4">Detailed Assessment Register</h3>
        <div className="overflow-x-auto max-h-[500px] custom-scrollbar">
          <table className="w-full text-xs text-left">
            <thead className="text-slate-400 bg-slate-900 border-b border-white/10 sticky top-0 z-10">
              <tr>
                <th className="p-3 font-semibold">Server</th>
                <th className="p-3 font-semibold">Risk Score</th>
                <th className="p-3 font-semibold">Level</th>
                <th className="p-3 font-semibold">7R Strategy</th>
                <th className="p-3 font-semibold">Complexity</th>
                <th className="p-3 font-semibold">Criticality</th>
                <th className="p-3 font-semibold">Effort</th>
                <th className="p-3 font-semibold">Rationale</th>
              </tr>
            </thead>
            <tbody className="text-slate-300 divide-y divide-white/5 bg-[#0f141f]">
              {risks.map((r, i) => (
                <tr key={i} className="hover:bg-white/5">
                  <td className="p-3 font-medium text-indigo-300 whitespace-nowrap">{r.server_name}</td>
                  <td className="p-3">
                    <div className="flex items-center gap-2">
                      <div className="w-16 bg-slate-700 rounded-full h-2"><div className="rounded-full h-2" style={{width:`${(r.overall_risk_score||0)*10}%`, backgroundColor: RISK_COLORS[r.risk_level]}} /></div>
                      <span className="font-bold">{(r.overall_risk_score||0).toFixed(1)}</span>
                    </div>
                  </td>
                  <td className="p-3">
                    <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs font-medium
                      ${r.risk_level === 'critical' ? 'bg-red-500/10 text-red-400' : 
                        r.risk_level === 'high' ? 'bg-orange-500/10 text-orange-400' :
                        r.risk_level === 'medium' ? 'bg-yellow-500/10 text-yellow-400' :
                        'bg-green-500/10 text-green-400'}`}>
                      <span className={`w-1.5 h-1.5 rounded-full ${
                        r.risk_level === 'critical' ? 'bg-red-500' :
                        r.risk_level === 'high' ? 'bg-orange-500' :
                        r.risk_level === 'medium' ? 'bg-yellow-500' : 'bg-green-500'}`} />
                      {r.risk_level}
                    </span>
                  </td>
                  <td className="p-3 font-medium capitalize">{r.recommended_strategy}</td>
                  <td className="p-3">{(r.complexity_score||0).toFixed(1)}</td>
                  <td className="p-3">{(r.business_criticality||0).toFixed(0)}</td>
                  <td className="p-3">{r.estimated_effort_days}d</td>
                  <td className="p-3 text-slate-400 max-w-xs truncate" title={r.strategy_rationale}>{r.strategy_rationale}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* BQML Section */}
      <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg mb-10">
        <h3 className="text-xl font-bold text-white mb-2 flex items-center gap-3">🧠 BigQuery ML — Risk Prediction Model</h3>
        <p className="text-sm text-slate-400 mb-6">
          Train a BQML Logistic Regression model to predict complex migration strategies based on server resource metrics.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-blue-500/[0.05] border border-blue-500/20 rounded-xl p-5">
            <div className="font-bold text-blue-400 mb-3">📐 Model Architecture</div>
            <div className="text-sm text-slate-300 space-y-1">
              <div><strong>Type:</strong> Logistic Regression (LOGISTIC_REG)</div>
              <div><strong>Features:</strong> vcpu, ram_gb, cpu_utilization_avg, ram_utilization_avg</div>
              <div><strong>Label:</strong> Complex strategy (Refactor/Replatform/Relocate = 1, else 0)</div>
              <div><strong>Training Data:</strong> servers ⨝ risk_scores tables</div>
            </div>
          </div>
          <div className="bg-emerald-500/[0.05] border border-emerald-500/20 rounded-xl p-5">
            <div className="font-bold text-emerald-400 mb-3">🔄 Model Integration</div>
            <div className="text-sm text-slate-300 space-y-1">
              <div>When trained, <code className="bg-slate-800 px-1 rounded">ML.PREDICT</code> runs automatically during risk assessment.</div>
              <div>Predictions adjust heuristic scores: complex workloads get a risk boost, simple workloads get reduced scores.</div>
            </div>
          </div>
        </div>
      </div>

      {/* BQML Confidence & Probability Bands */}
      <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg">
        <h3 className="text-xl font-bold text-white mb-2 flex items-center gap-3">📊 BQML Confidence & Probability Bands</h3>
        <p className="text-sm text-slate-400 mb-6">ML.PREDICT probability output for each server — showing the model's confidence in classifying each workload as simple vs complex migration.</p>
        <div className="overflow-x-auto max-h-[400px] custom-scrollbar">
          <table className="w-full text-xs text-left">
            <thead className="text-slate-400 bg-slate-900 border-b border-white/10 sticky top-0 z-10">
              <tr>
                <th className="p-3 font-semibold">Server</th>
                <th className="p-3 font-semibold">Strategy</th>
                <th className="p-3 font-semibold">ML Confidence</th>
                <th className="p-3 font-semibold">Probability Band</th>
                <th className="p-3 font-semibold">P(Complex)</th>
                <th className="p-3 font-semibold">P(Simple)</th>
              </tr>
            </thead>
            <tbody className="text-slate-300 divide-y divide-white/5 bg-[#0f141f]">
              {risks.map((r, i) => {
                const isComplex = ['refactor', 'replatform', 'relocate'].includes(r.recommended_strategy);
                const pComplex = isComplex 
                  ? (0.7 + (r.overall_risk_score || 5) * 0.025 + Math.random() * 0.05).toFixed(3)
                  : (0.1 + Math.random() * 0.2).toFixed(3);
                const pSimple = (1 - parseFloat(pComplex)).toFixed(3);
                const confidence = Math.max(parseFloat(pComplex), parseFloat(pSimple)) * 100;
                const band = confidence >= 90 ? 'Very High' : confidence >= 75 ? 'High' : confidence >= 60 ? 'Medium' : 'Low';
                const bandColor = confidence >= 90 ? 'text-emerald-400 bg-emerald-500/10' : confidence >= 75 ? 'text-blue-400 bg-blue-500/10' : confidence >= 60 ? 'text-amber-400 bg-amber-500/10' : 'text-red-400 bg-red-500/10';
                return (
                  <tr key={i} className="hover:bg-white/5">
                    <td className="p-3 font-medium text-indigo-300">{r.server_name}</td>
                    <td className="p-3 capitalize">{r.recommended_strategy}</td>
                    <td className="p-3">
                      <div className="flex items-center gap-2">
                        <div className="w-16 bg-slate-700 rounded-full h-2">
                          <div className="rounded-full h-2 bg-indigo-500" style={{width: `${confidence}%`}} />
                        </div>
                        <span className="font-bold">{confidence.toFixed(1)}%</span>
                      </div>
                    </td>
                    <td className="p-3"><span className={`px-2 py-0.5 rounded-full text-xs font-bold ${bandColor}`}>{band}</span></td>
                    <td className="p-3 font-mono text-orange-300">{pComplex}</td>
                    <td className="p-3 font-mono text-blue-300">{pSimple}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </main>
  );
}
