import React, { useState } from 'react';
import axios from 'axios';
import { Users, Mail, FileText, Download, Send, CheckCircle2, Loader2, AlertCircle } from 'lucide-react';

const STAKEHOLDERS = [
  { name: 'Sarah Chen', role: 'CTO', email: 'sarah.chen@acmecorp.com', group: 'Executive' },
  { name: 'Raj Patel', role: 'VP Infrastructure', email: 'raj.patel@acmecorp.com', group: 'Executive' },
  { name: 'Emily Rodriguez', role: 'Cloud Architect', email: 'emily.r@acmecorp.com', group: 'Technical' },
  { name: 'David Kim', role: 'Security Lead', email: 'david.kim@acmecorp.com', group: 'Technical' },
  { name: 'Lisa Wang', role: 'FinOps Manager', email: 'lisa.wang@acmecorp.com', group: 'Finance' },
  { name: 'Michael Brown', role: 'Program Manager', email: 'm.brown@acmecorp.com', group: 'PMO' },
];

const REPORT_TEMPLATES = [
  { name: 'Executive Summary', desc: 'High-level migration progress, risk posture, and cost savings for C-suite.', audience: 'Executive', prompt: 'Generate an executive summary report for our cloud migration project. Include key metrics: 10,000 servers discovered, 5 migration waves planned, 52.4% estimated cost savings ($1.2M annually). Cover risk posture, wave progress, and strategic recommendations.' },
  { name: 'Technical Deep Dive', desc: 'Detailed wave plan, architecture mappings, and dependency analysis.', audience: 'Technical', prompt: 'Generate a technical deep-dive report covering: server inventory analysis (10,000 servers across VMware), wave planning (5 waves with dependency-aware sequencing), GCP architecture mappings (Compute Engine, Cloud SQL, GKE, Memorystore), and application dependency topology.' },
  { name: 'FinOps Report', desc: 'TCO comparison, cost optimization recommendations, and ROI projections.', audience: 'Finance', prompt: 'Generate a FinOps report covering: on-premises vs GCP cost comparison, TCO analysis with 52.4% savings projection ($1.2M/year), cost optimization drivers (committed use discounts, right-sizing, spot VMs), and 3-year ROI projections.' },
  { name: 'Compliance Report', desc: 'Framework compliance status, control mappings, and security posture.', audience: 'Technical', prompt: 'Generate a compliance and security report covering: HIPAA (66%), PCI-DSS (83%), SOC2 (80%), ISO27001 (80%) compliance coverage, GCP security control mappings, zero-trust architecture recommendations, and remediation priorities.' },
];

export default function StakeholderComm() {
  const [selectedGroup, setSelectedGroup] = useState('All');
  const [generating, setGenerating] = useState(null);
  const [generatedReports, setGeneratedReports] = useState({});
  const [notification, setNotification] = useState(null);

  const groups = ['All', ...Array.from(new Set(STAKEHOLDERS.map(s => s.group)))];
  const filtered = selectedGroup === 'All' ? STAKEHOLDERS : STAKEHOLDERS.filter(s => s.group === selectedGroup);

  const generateReport = async (template, index) => {
    setGenerating(index);
    try {
      const res = await axios.post('http://localhost:8000/api/chat', { prompt: template.prompt });
      const reportContent = res.data?.reply || 'Report generation failed.';
      setGeneratedReports(prev => ({ ...prev, [index]: reportContent }));
      
      // Auto-download as markdown
      const blob = new Blob([`# ${template.name}\n\n_Generated by D.A.M.I. AI — ${new Date().toLocaleString()}_\n\n---\n\n${reportContent}`], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `DAMI_${template.name.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0,10)}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      setNotification({ type: 'success', text: `${template.name} generated and downloaded!` });
    } catch {
      setNotification({ type: 'error', text: 'Failed to generate report. Check backend.' });
    } finally {
      setGenerating(null);
      setTimeout(() => setNotification(null), 4000);
    }
  };

  const sendEmail = (template, index) => {
    const recipients = STAKEHOLDERS.filter(s => 
      template.audience === 'Executive' ? s.group === 'Executive' :
      template.audience === 'Finance' ? s.group === 'Finance' :
      ['Technical', 'PMO'].includes(s.group)
    );
    const emails = recipients.map(r => r.email).join(',');
    const subject = encodeURIComponent(`D.A.M.I. ${template.name} — ${new Date().toLocaleDateString()}`);
    const body = encodeURIComponent(`Hi,\n\nPlease find attached the latest ${template.name} from the D.A.M.I. Migration Intelligence Platform.\n\nKey Highlights:\n- ${template.desc}\n\nBest regards,\nD.A.M.I. Automated Reports`);
    window.open(`mailto:${emails}?subject=${subject}&body=${body}`, '_blank');
    setNotification({ type: 'success', text: `Email draft opened for ${recipients.length} recipients` });
    setTimeout(() => setNotification(null), 4000);
  };

  return (
    <main className="flex-1 bg-[#0b0f19] text-white flex flex-col h-full overflow-y-auto p-10 pb-20 custom-scrollbar relative z-10">
      <header className="mb-8">
        <h1 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400 tracking-tight mb-2">Stakeholder Communications</h1>
        <p className="text-slate-400 font-medium">Manage stakeholders and generate tailored migration reports for different audiences.</p>
      </header>
      <div className="h-px bg-white/10 w-full mb-8" />

      {/* Notification */}
      {notification && (
        <div className={`mb-6 p-4 rounded-xl flex items-center gap-3 text-sm font-medium border ${notification.type === 'success' ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300' : 'bg-red-500/10 border-red-500/30 text-red-300'}`}>
          {notification.type === 'success' ? <CheckCircle2 className="w-4 h-4" /> : <AlertCircle className="w-4 h-4" />}
          {notification.text}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Stakeholder Directory */}
        <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-xl font-bold text-white flex items-center gap-2"><Users className="w-5 h-5 text-indigo-400" /> Stakeholder Directory</h3>
            <select value={selectedGroup} onChange={e => setSelectedGroup(e.target.value)} className="bg-slate-900 border border-white/10 rounded-lg px-3 py-1.5 text-xs text-white">{groups.map(g => <option key={g}>{g}</option>)}</select>
          </div>
          <div className="space-y-3">
            {filtered.map((s, i) => (
              <div key={i} className="flex items-center gap-4 p-4 bg-slate-900/30 rounded-xl border border-white/5 hover:bg-white/5 transition-colors">
                <div className="w-10 h-10 rounded-full bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center text-indigo-300 font-bold text-sm">{s.name.split(' ').map(n => n[0]).join('')}</div>
                <div className="flex-1">
                  <div className="font-bold text-white text-sm">{s.name}</div>
                  <div className="text-xs text-slate-400">{s.role}</div>
                </div>
                <span className="text-xs bg-slate-800 text-slate-400 px-2 py-0.5 rounded-full">{s.group}</span>
                <button onClick={() => { window.open(`mailto:${s.email}?subject=D.A.M.I. Migration Update`, '_blank'); }} className="p-2 rounded-lg bg-slate-800 border border-white/10 text-slate-400 hover:text-white transition-colors"><Mail className="w-4 h-4" /></button>
              </div>
            ))}
          </div>
        </div>

        {/* Report Templates */}
        <div className="bg-[#131826] rounded-xl p-6 border border-white/[0.05] shadow-lg">
          <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2"><FileText className="w-5 h-5 text-amber-400" /> Report Templates</h3>
          <div className="space-y-4">
            {REPORT_TEMPLATES.map((r, i) => (
              <div key={i} className="p-4 bg-slate-900/30 rounded-xl border border-white/5">
                <div className="flex items-center justify-between mb-2">
                  <div className="font-bold text-white text-sm">{r.name}</div>
                  <span className="text-xs bg-indigo-500/10 text-indigo-400 px-2 py-0.5 rounded-full">{r.audience}</span>
                </div>
                <p className="text-xs text-slate-400 mb-3">{r.desc}</p>
                <div className="flex gap-2">
                  <button 
                    onClick={() => generateReport(r, i)} 
                    disabled={generating !== null}
                    className="flex-1 bg-indigo-600/20 border border-indigo-500/30 text-indigo-300 hover:bg-indigo-600/30 px-3 py-2 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-1.5 disabled:opacity-50"
                  >
                    {generating === i ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating...</> : <><Download className="w-3.5 h-3.5" /> Generate Report</>}
                  </button>
                  <button 
                    onClick={() => sendEmail(r, i)}
                    className="flex-1 bg-slate-800 border border-white/10 text-slate-300 hover:bg-white/5 px-3 py-2 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-1.5"
                  >
                    <Send className="w-3.5 h-3.5" /> Email
                  </button>
                </div>
                {generatedReports[i] && (
                  <div className="mt-3 p-3 bg-slate-900/50 rounded-lg border border-white/5 max-h-40 overflow-y-auto custom-scrollbar">
                    <pre className="text-[10px] text-slate-400 whitespace-pre-wrap font-sans">{generatedReports[i].substring(0, 500)}...</pre>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </main>
  );
}
